version: '3'
services:
  web:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports: 
      - '80:80'
    depends_on:
      - db
      - mosquitto
    networks:
      project_vlan:
        ipv4_address: 192.168.1.155

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      project_vlan:
        ipv4_address: 192.168.1.156

  mosquitto:
    # Use root/example as user/password credentials for db
    image: eclipse-mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mqtt_broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      project_vlan:
        ipv4_address: 192.168.1.157
        
networks:
  project_vlan:
    name: project_vlan
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/16