version: '3'
services:

  web:
    container_name: web
    image: armandojp/iot-web-server
    # build:
    #   context: ./server
    restart: always
    ports: 
      - '80:80'
    links:
      - mongo
      - mosquitto
    depends_on:
      - mongo
      - mosquitto

  mongo:
    container_name: mongo
    image: mongo:5.0.4
    restart: always
    volumes: 
      - mongodb/data:/data/db
    ports:
      - '27017:27017'

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.14
    # volumes:
    #   - mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports: 
    - '1883:1883'
    - '9001:9001'

volumes:
  mongodb:
  mosquitto:
