apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-claim0
  name: mongo-claim0

spec:
  # The volume can only be accessed by a single node. Multiple pods on the same
  # node can access the volume.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi # Mebibye; 100* 2^20; 
status: {}
