apiVersion: apps/v1
kind: Deployment

metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mosquitto
  name: mosquitto

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mosquitto
  strategy: {}

  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mosquitto
    spec:
      containers:
        - image: eclipse-mosquitto:2.0.14
          name: mosquitto
          ports:
            - containerPort: 1883
            - containerPort: 9001

          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
              
          resources: {}
      restartPolicy: Always

      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
status: {}
