apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |-
    persistence true
    allow_anonymous true
    connection_messages true
    # log_type all
    listener 1883
    # socket_domain ipv4