apiVersion: apps/v1
kind: Deployment

metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web

spec:
  # How many copies of each pod do we want?
  replicas: 1
  # Which pods are managed by this deployment?
  selector:
    matchLabels:
      io.kompose.service: web
  # How do we want to update the pods? Default: rolling deployment
  strategy: {}

  # This template field is a regular pod configuration 
  # nested inside the deployment spec.
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      # Set labels on the pod.
      # This is used in the deployment selector
      labels:
        io.kompose.service: web
    spec:
      containers:
        - image: <replace_during_deployment>
          name: web
          envFrom:
          - secretRef:
              name: app-secret
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always

status: {}
